COLOR_TITLE_1_TEXT = "#f14e47"
COLOR_TITLE_2_TEXT = "#05468a"
COLOR_NORMAL_TEXT = "#000000"

OFFER_SELECTION_COLOR_TITLE_1_TEXT = "#000000"
OFFER_SELECTION_COLOR_TITLE_2_TEXT = "#000000"
OFFER_SELECTION_COLOR_NORMAL_TEXT = "#000000"

COLOR_APP_BACKGROUND = "#ffffff"
COLOR_OFFERS_BACKGROUND = "#e5f7fb"
COLOR_FUTURE_TRAVELS_BACKGROUND = "#f4f9e3"
COLOR_PROFILE_BACKGROUND = "#e5e5e5"
COLOR_NEW_OFFER_BACKGROUND = "#f4f4fe"
COLOR_OFFER_SELECTION_BACKGROUND = "#fff5ec"

COLOR_OFFERS_TITLE_BACKGROUND = "#adefff"
COLOR_FUTURE_TRAVELS_TITLE_BACKGROUND = "#c1fdb3"
COLOR_PROFILE_TITLE_BACKGROUND = "#fabfbc"
COLOR_NEW_OFFER_TITLE_BACKGROUND = "#d0d5fd"
COLOR_OFFER_SELECTION_TITLE_BACKGROUND = "#fff5ec"

COLOR_OFFER_SELECTION_BUTTON_BACKGROUND = '#f1ebed'
