COLOR_TITLE_1_TEXT = "#f14e47"
COLOR_TITLE_2_TEXT = "#05468a"
COLOR_NORMAL_TEXT = "#000000"

COLOR_APP_BACKGROUND = "#ffffff"
COLOR_OFFERS_BACKGROUND = "#e5f7fb"
COLOR_FUTURE_TRAVELS_BACKGROUND = "#f4f9e3"
COLOR_PROFILE_BACKGROUND = "#e5e5e5"
COLOR_NEW_OFFER_BACKGROUND = "#f4f4fe"

COLOR_OFFERS_TITLE_BACKGROUND = "#adefff"
COLOR_FUTURE_TRAVELS_TITLE_BACKGROUND = "#c1fdb3"
COLOR_PROFILE_TITLE_BACKGROUND = "#fabfbc"
COLOR_NEW_OFFER_TITLE_BACKGROUND = "#d0d5fd"

